# CENSO

Para calcular el nivel socioecononico voy a usar la siguiente metodología. Tomando:

1. Número de hogares con computadora: Indica la cantidad de hogares que tienen al menos una computadora.

2. Porcentaje de menores de 18 años asistiendo a establecimientos educativos: Calculado como la proporción de menores de 18 años que asisten a algún establecimiento educativo respecto al total de menores de 18 años.

3. Porcentaje de habitantes mayores de 25 años con nivel universitario completo: Calculado como la proporción de habitantes mayores de 25 años con nivel universitario completo respecto al total de habitantes mayores de 25 años.

$IndiceComputadora = \frac{NúmeroDeHogaresConComputadora}{ConComputadora \cup ConHeladera \cup ConCelular \cup ConTeléfono}$

$IndiceEscolaridad = \frac{MenoresDe18Asisten}{MenoresDe18}$

$IndiceEducSuperior = \frac{MayoresDe25Universitarios}{MayoresDe25}$

PC1=0.76120783∗IndiceEducSup+0.10759338∗IndiceEscolaridad+0.63952037∗IndiceCompu

El PC1 arroja un rango de valores entre 0 y 1.32 (aproximadamente) se procede a una normalización para facilitar la lectura de los valores.

$NSE = \frac{PC1}{PC1Max} * 10$

De esta manera todos los valores del índice de NSE de radios censales se expresan en una escala del 0 al 10, donde 10 es el máximo valor de NSE alcanzado por el primer radio censal del ranking y 0 es el mínimo 

(fuente: https://gcba.github.io/tod/nota_metodologica#2-estimacion-del-nivel-socioeconomico-de-un-radio-censal)

Valor Bajo (0-3): Puede indicar un nivel socioeconómico bajo, con posiblemente menos acceso a recursos y oportunidades.

Valor Medio (4-7): Podría sugerir un nivel socioeconómico medio, con un acceso moderado a recursos y oportunidades.

Valor Alto (8-10): Indicaría un nivel socioeconómico relativamente alto, con un buen acceso a recursos y oportunidades.

# Comuna 1


In [29]:
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import  seaborn as sns
from sklearn.decomposition import PCA 

In [22]:
#primero calculo los indices 
NumeroDeHogaresConComputadora = 51500
ConComputadora = 51500
ConHeladera = 77558
ConCelular = 73457
ConTelefono = 60208

# Calcula el índice de computadora
IndiceComputadora = NumeroDeHogaresConComputadora / (ConComputadora + ConHeladera + ConCelular + ConTelefono)


print("Índice de Computadora:", IndiceComputadora)

Índice de Computadora: 0.19602394917841223


In [23]:
MenoresDe18Asisten = 2985+1991+13712+3865+5164
MenoresDe18 = 4162+2130+13922+4010+5958
IndiceEscolaridad = MenoresDe18Asisten / MenoresDe18
print("Índice de Escolaridad:", IndiceEscolaridad)

Índice de Escolaridad: 0.9183288052481612


In [24]:
MayoresDe25Universitarios = 14687
MayoresDe25 = 25118+21421+121658
IndiceEducSuperior = MayoresDe25Universitarios / MayoresDe25
print("Índice de Educación Superior:", IndiceEducSuperior)

Índice de Educación Superior: 0.08732022568773522


In [30]:
#ahora calculo la amtriz
matriz_correlaciones = np.array([
    [1, IndiceEducSuperior, IndiceComputadora],
    [IndiceEducSuperior, 1, IndiceEscolaridad],
    [IndiceComputadora, IndiceEscolaridad, 1]
])
#analisis de lso componenete principales
pca = PCA(n_components=3)
pca.fit(matriz_correlaciones)

#los componentes principales y la varianza explicada
componentes_principales = pca.components_
varianza_explicada = pca.explained_variance_ratio_

print("\nComponentes Principales:")
print(componentes_principales)

print("\nVarianza Explicada:")
print(varianza_explicada)


Componentes Principales:
[[ 0.59696031 -0.60562202 -0.52617522]
 [ 0.46662516 -0.27140543  0.84178385]
 [-0.65260964 -0.74803815  0.1205802 ]]

Varianza Explicada:
[9.92815398e-01 7.18460163e-03 1.77381678e-32]


In [25]:
# Calcula el primer componente principal (PC1)
PC1 = 0.76120783 * IndiceEducSuperior + 0.10759338 * IndiceEscolaridad + 0.63952037 * IndiceComputadora
print("PC1:", PC1)

PC1: 0.29063624812632194


In [32]:
#normalizar PC1
PC1Max = varianza_explicada[0]
NSE = (PC1 / PC1Max) * 10
print (NSE)

2.9273946456024857
