# CENSO

Para calcular el nivel socioecononico voy a usar la siguiente metodología. Tomando:

1. Número de hogares con computadora: Indica la cantidad de hogares que tienen al menos una computadora.

2. Porcentaje de menores de 18 años asistiendo a establecimientos educativos: Calculado como la proporción de menores de 18 años que asisten a algún establecimiento educativo respecto al total de menores de 18 años.

3. Porcentaje de habitantes mayores de 25 años con nivel universitario completo: Calculado como la proporción de habitantes mayores de 25 años con nivel universitario completo respecto al total de habitantes mayores de 25 años.

$IndiceComputadora = \frac{NúmeroDeHogaresConComputadora}{ConComputadora \cup ConHeladera \cup ConCelular \cup ConTeléfono}$

$IndiceEscolaridad = \frac{MenoresDe18Asisten}{MenoresDe18}$

$IndiceEducSuperior = \frac{MayoresDe25Universitarios}{MayoresDe25}$

PC1=0.76120783∗IndiceEducSup+0.10759338∗IndiceEscolaridad+0.63952037∗IndiceCompu

El PC1 arroja un rango de valores entre 0 y 1.32 (aproximadamente) se procede a una normalización para facilitar la lectura de los valores.

$NSE = \frac{PC1}{PC1Max} * 10$

De esta manera todos los valores del índice de NSE de radios censales se expresan en una escala del 0 al 10, donde 10 es el máximo valor de NSE alcanzado por el primer radio censal del ranking y 0 es el mínimo 

(fuente: https://gcba.github.io/tod/nota_metodologica#2-estimacion-del-nivel-socioeconomico-de-un-radio-censal)

Valor Bajo (0-3): Puede indicar un nivel socioeconómico bajo, con posiblemente menos acceso a recursos y oportunidades.

Valor Medio (4-7): Podría sugerir un nivel socioeconómico medio, con un acceso moderado a recursos y oportunidades.

Valor Alto (8-10): Indicaría un nivel socioeconómico relativamente alto, con un buen acceso a recursos y oportunidades.

# Comuna 1


In [29]:
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import  seaborn as sns
from sklearn.decomposition import PCA 

In [33]:
def calcular_indice_computadora(numero_hogares_con_computadora, con_computadora, con_heladera, con_celular, con_telefono):
    indice_computadora = numero_hogares_con_computadora / (con_computadora + con_heladera + con_celular + con_telefono)
    return indice_computadora

# Parámetros para comuna 1
numero_hogares_con_computadora_c1 = 51500
con_computadora_c1 = 51500
con_heladera_c1 = 77558
con_celular_c1 = 73457
con_telefono_c1 = 60208

# Calcular el índice de computadora 
indice_computadora_c1 = calcular_indice_computadora(numero_hogares_con_computadora_c1, con_computadora_c1, con_heladera_c1, con_celular_c1, con_telefono_c1)

print("Índice de Computadora - Comuna 1:", indice_computadora_c1)

Índice de Computadora - Comuna 1: 0.19602394917841223


In [34]:
def calcular_indice_escolaridad(menores_de_18_asisten, menores_de_18):
    indice_escolaridad = menores_de_18_asisten / menores_de_18
    return indice_escolaridad


menores_de_18_asisten_c1 = 2985 + 1991 + 13712 + 3865 + 5164
menores_de_18_c1 = 4162 + 2130 + 13922 + 4010 + 5958

# Calcular el índice de escolaridad para comuna 1
indice_escolaridad_c1 = calcular_indice_escolaridad(menores_de_18_asisten_c1, menores_de_18_c1)

print("Índice de Escolaridad - Comuna 1:", indice_escolaridad_c1)

Índice de Escolaridad - Comuna 1: 0.9183288052481612


In [35]:
def calcular_indice_educacion_superior(mayores_de_25_universitarios, mayores_de_25):
    indice_educacion_superior = mayores_de_25_universitarios / mayores_de_25
    return indice_educacion_superior

# Parámetros para comuna 1
mayores_de_25_universitarios_c1 = 14687
mayores_de_25_c1 = 25118 + 21421 + 121658

# Calcular el índice de educación superior para comuna 1
indice_educacion_superior_c1 = calcular_indice_educacion_superior(mayores_de_25_universitarios_c1, mayores_de_25_c1)

print("Índice de Educación Superior - Caso 1:", indice_educacion_superior_c1)

Índice de Educación Superior - Caso 1: 0.08732022568773522


In [37]:
def calcular_pca(indice_educacion_superior, indice_escolaridad, indice_computadora, n_components=3):
    # Calcula la matriz 
    matriz_correlaciones = np.array([
        [1, indice_educacion_superior, indice_computadora],
        [indice_educacion_superior, 1, indice_escolaridad],
        [indice_computadora, indice_escolaridad, 1]
    ])

    # Realiza el análisis de componentes principales
    pca = PCA(n_components=n_components)
    pca.fit(matriz_correlaciones)

    # Obtiene los componentes principales y la varianza explicada
    componentes_principales = pca.components_
    varianza_explicada = pca.explained_variance_ratio_

    return componentes_principales, varianza_explicada

componentes_principales, varianza_explicada = calcular_pca(indice_educacion_superior_c1, indice_escolaridad_c1, indice_computadora_c1)

print("\nComponentes Principales:")
print(componentes_principales)

print("\nVarianza Explicada:")
print(varianza_explicada)


Componentes Principales:
[[ 0.59696031 -0.60562202 -0.52617522]
 [ 0.46662516 -0.27140543  0.84178385]
 [-0.65260964 -0.74803815  0.1205802 ]]

Varianza Explicada:
[9.92815398e-01 7.18460163e-03 1.77381678e-32]


In [38]:
def calcular_pc1(indice_educacion_superior, indice_escolaridad, indice_computadora):
    # Coeficientes para el cálculo de PC1
    coef_educ_sup = 0.76120783
    coef_escolaridad = 0.10759338
    coef_computadora = 0.63952037

    # Calcula PC1
    pc1 = coef_educ_sup * indice_educacion_superior + coef_escolaridad * indice_escolaridad + coef_computadora * indice_computadora

    return pc1

# Calcula PC1
pc1_resultado = calcular_pc1(indice_educacion_superior_c1, indice_escolaridad_c1, indice_computadora_c1)
print("PC1:", pc1_resultado)

PC1: 0.29063624812632194


In [39]:
def normalizar_pc1(pc1, pc1_max):
    # Normaliza PC1
    nse = (pc1 / pc1_max) * 10
    return nse

pc1_max = varianza_explicada [0]

# Normaliza PC1
nse_resultado = normalizar_pc1(pc1_resultado, pc1_max)
print("NSE:", nse_resultado)

NSE: 2.9273946456024857
